### ISSUE TITLE
Compatibility issue with serialport >4.0.0

### ISSUE THREAD

**Issue by s1gmund80** [normen/homebridge-433-arduino#12]
In recent version of serialport (>4.0.0) it is not possible to set the ReadLine parser as before: 
  parser: SerialPort.parsers.readline("\n")

So to be compliant with the newver version of the library  in the inizialization of the Port there should be something like: 

            port = new SerialPort(self.config.serial_port_in, {baudRate: 9600});
            inPort = port.pipe(new Readline({ delimiter: '\n' }))

**Comment by normen** [comment]
Yeah, thats why I set the version to ^4.0.0 to stay compatible. Theres really no need for me to go to a more recent version but maybe with another change in the future I'll change this.

**Comment by s1gmund80** [comment]
Ok, in any case since a recent (forced) update of all the stack i was not able anymore to build and use old serialport versions, so i forked the project just to apply the changes needed to be compliant with current serialport version 7.1.0
If someday you would like to update your project here the fix: https://github.com/s1gmund80/homebridge-433-arduino/blob/master/index.js
It is working fine now for me
Thank you for plugin, the best so far for me! :)

**Comment by normen** [comment]
Thanks. Thats funny though, a normal install shouldn't require that. Maybe in your installation you have a global serialport install that somehow gets used?

**Comment by normen** [comment]
fixed in 0.9.8
