### ISSUE TITLE
Support for temperature sensor

### ISSUE THREAD

**Issue by jonalbr** [normen/homebridge-433-arduino#21]
Hi,
in my enviroment is a temperature sensor sending from a cheap 'weather station'. My 433MHz reciver gets these messages:

`[Arduino RC Switch Platform] {"type":"auriol","message":{"id":14,"temperature":12.9,"battery":1,"channel":1}}`

Is there a possibility how I can use these information as a temperture sensor in HomeKit?

Thanks

**Comment by normen** [comment]
You'd need to extend the library with a new device type as temperature sensors are currently not supported by the plugin..
