### ISSUE TITLE
Support for multiple Arduinos

### ISSUE THREAD

**Issue by ituri** [normen/homebridge-433-arduino#23]
I really like the idea to use an ESP8266 to separate the homebridge- from the transceiver part. 

Would it be possible to use multiple Arduinos? My Pi with homebridge is located in the basement, my Arduino on the ground floor but I want also to be able to send signals two floors up from there. Putting another Arduino on the first floor would help a lot there.

**Comment by normen** [comment]
Sure. You can add multiple platform entries in your config.json. I am using one Micro connected via USB and two ESPs via WiFi.
