### ISSUE TITLE
Motion Sensor with multiple codes?

### ISSUE THREAD

**Issue by danricho** [normen/homebridge-433-arduino#26]
Is there a way to register multiple Code/Pule/Protocol combinations to one Motion Sensor accessory? Or a way of setting wildcards in those attributes?
I currently have 3 accessories defined for one actual doorbell, due to the code varying slightly.

```
"motion": [
    {
        "name": "Door Bell 1",
        "code": 357636,
        "pulse": 169,
        "protocol": 1
    },
    {
        "name": "Door Bell 2",
        "code": 357637,
        "pulse": 169,
        "protocol": 1
    },
    {
        "name": "Door Bell 3",
        "code": 357679,
        "pulse": 169,
        "protocol": 1
    }
]
```

This would be awesome:
```
"motion": [
    {
        "name": "Door Bell",
        "code": [357636,357637,357679]
        "pulse": [169,170]
        "protocol": [1]
    }
]
```

**Comment by normen** [comment]
No there isn't but often the devices that switch codes work with other code combinations (see wiki).. Maybe also try using ESPiLight?

**Comment by danricho** [comment]
ESPiLight and found that for some other devices it didn't detect very well.

No problem though. I was asking in case I had missed a way of implementing with multiple code options.

Thanks for the great system!
