### ISSUE TITLE
Switch on HomeKit not triggering actiong

### ISSUE THREAD

**Issue by s1gmund80** [normen/homebridge-433-arduino#8]
Hi, great work!
I've been able to use everything in the project, but the switches appeared in Homekit are not able to do nothing: there is no way to trigger an action or to use them as an event to trigger scene...
Why? Does it depends on the status of themselves? When i push the 433 button i see it on the homebridge logs and I see for a second the switch in the Home app that become ON and then OFF again.

thx
i

**Comment by normen** [comment]
Sounds like you set up buttons instead of switches. Re-read the manual.

Please understand that I can't give support for this free software. Please only use this bug tracker for actual bug reports with proper information.

**Comment by s1gmund80** [comment]
You are right, 
i used the wrong key-word: i configured them as buttons, not switch, since they are buttons.

What I can’t see on the manual is if there are any constraints to be satisfied to use them i  the Homekit framework: with the basic configuration they seams useless. They can’t be used to trigger any action/scene

In any case I understand what you mean, i know it is not a product, but i guess so far it is the best solution i found to handle the 433/homekit connection, so if i can contribute in any way... 

Inviato da iPhone

**Comment by normen** [comment]
Yes you can trigger scenes in HomeKit with any switch that you see, including the switches and buttons this plugin creates. I use it every day. But that has nothing to do with this plugin, read the HomeKit / Home App documentation for how that works.

**Comment by s1gmund80** [comment]
In fact they should, but it was impossible to me to use the buttons as triggers until i defined also some switches with the same codes.


Inviato da iPhone

**Comment by normen** [comment]
I don‘t think thats the issue, I do and I can. Most probably you didn‘t wait long enough after setting up the button or scene or did something else wrong. Either way no bug in this plugin.
