### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by iamdeeff** [normen/homebridge-433-arduino#9]
When I try to install the plugin on my Raspberry Pi 3, I get this warning:

npm i homebridge-433-arduino
\
> serialport@4.0.7 install /home/pi/node_modules/homebridge-433-arduino/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v46-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@4.6.2 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/pi/node_modules/homebridge-433-arduino/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport_unix.o
  CXX(target) Release/obj.target/serialport/src/serialport_poller.o
  SOLINK_MODULE(target) Release/obj.target/serialport.node
  COPY Release/serialport.node
make: Leaving directory '/home/pi/node_modules/homebridge-433-arduino/node_modules/serialport/build'
homebridge-433-arduino@0.9.4 node_modules/homebridge-433-arduino
└── serialport@4.0.7 (bindings@1.2.1, commander@2.14.1, debug@2.6.9, lie@3.2.0, nan@2.8.0, object.assign@4.1.0)

**Comment by normen** [comment]
Read the log. It says it couldn't download binaries and then proceeded to build them instead. From what I see you have a proper install of the plugin. So I suspect you didn't even try if it works and posted this issue right away because the log said "ERROR" somewhere?
